# Generated by Django 4.2.1 on 2023-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_hotelstaff_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room/')),
                ('star', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(blank=True, null=True)),
                ('person', models.IntegerField(default=1)),
                ('bed_choice', models.CharField(choices=[('One bed', 'One'), ('Two bed', 'Two')], default='One bed', max_length=50)),
                ('wifi', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('condition', models.BooleanField(default=False)),
                ('dostovka', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
            ],
        ),
    ]
