# Generated by Django 4.2.1 on 2023-08-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='elevator',
            new_name='elevators',
        ),
    ]
