# Generated by Django 4.2.1 on 2023-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_elevator_room_elevators'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sqm',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
