# Generated by Django 4.2.1 on 2023-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_room_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelstaff',
            name='company',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='experience',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='language_skill',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='phone_number',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
