# Generated by Django 4.2.1 on 2023-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hotelstaff_company_hotelstaff_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelstaff',
            name='language_skill',
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='language_skill1',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='language_skill2',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='language_skill3',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='hotelstaff',
            name='language_skill4',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
